# Generated by Django 2.2.13 on 2022-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_expand_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='assessmentfeedback',
            name='feedback_text',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='assessmentpart',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
